# Workshop 8 [Student]

This notebook will cover the following topics:

1. Numpy Array
2. Reading data from CSV
3. Statistics
4. Indexing
5. Copy vs View
6. Modifications

## 8.1 NUMPY ARRAY (Follow)

**Learning Objectives:**

1. Understand the numpy module.
2. Understand numpy arrays.
3. Understand Array creation and basic functions.
4. Learn to manipulate arrays

In [ ]:
#https://numpy.org/doc/stable/reference/arrays.dtypes.html
"""
Add comments for you own reference
"""

import numpy as np
x = np.array([[1,2,3,4,5],
                 [6,7,8,9,0],
                 [5,4,3,2,1]])
print(x)
print("Type -",type(x))
print("Data Type -",x.dtype)
print("Size -",x.size)
print("ItemSize -",x.itemsize)
print("Dimensions -",x.ndim)
print("Shape -",x.shape)

In [96]:
x = np.full([4,2,3],3) #items, rows, columns
print(x.shape)
print(x,"\n")

(4, 2, 3)
[[[3 3 3]
  [3 3 3]]

 [[3 3 3]
  [3 3 3]]

 [[3 3 3]
  [3 3 3]]

 [[3 3 3]
  [3 3 3]]] 



In [98]:
"""
Add comments for you own reference
"""

import numpy as np
x = np.full(5,3)
print("Full:\n",x)
x = np.zeros((2,4))
print("Zeros:\n",x)
x = np.ones((2,5))
print("Ones:\n",x)
x = np.arange(1,7)
print("Range:\n",x)
x = np.linspace(1,5,6) #(5-1) / (6-1)
print("LinSpace:\n",x)

Full:
 [3 3 3 3 3]
Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Range:
 [1 2 3 4 5 6]
LinSpace:
 [1.  1.8 2.6 3.4 4.2 5. ]


In [100]:
"""
Add comments for you own reference
"""

import numpy as np
x = np.arange(1,10)
print("Array X:\n",x,"\n")
print("Multiplication:\n",x*2,"\n")
print("Substraction:\n",x-2,"\n")
y = np.arange(3,12)
print("Array Y:\n",y,"\n")
print("SHAPES -",x.shape,y.shape,"\n")
print("Addition:\n",x+y,"\n")
print("Multiplication:\n",x*y,"\n")

Array X:
 [1 2 3 4 5 6 7 8 9] 

Multiplication:
 [ 2  4  6  8 10 12 14 16 18] 

Substraction:
 [-1  0  1  2  3  4  5  6  7] 

Array Y:
 [ 3  4  5  6  7  8  9 10 11] 

SHAPES - (9,) (9,) 

Addition:
 [ 4  6  8 10 12 14 16 18 20] 

Multiplication:
 [ 3  8 15 24 35 48 63 80 99] 



**Evaluation:**

After running this program, think about and answer these questions:

1. What does the arange function do? The arange function gives evenly spaced values wihtin a given interval. 
2. What is the use of 1s and 0s function? The use is for axis and dimensions. 
3. What will happen if shapes of arrays are not same? You would have to resize it.
4. Try to add more dimentions to the arrays.

## 8.1 NUMPY ARRAY (Group)

Write a program that will do the following:

1. Create 3 Arrays:
    - X : containing Multiples of 5
    - Y : in range of 100 to 150
    - Z : containing all n (taken from user) 
2. Make sure that Shapes of arrays are equal.
3. Perform:
    - X + Y
    - X * Z
    - Z - Y
    - X + Y + Z

In [117]:
#### import numpy as np

#create array with multiples of 5
x = np.array([[5, 10, 15, 20, 25, 30] , [35, 40, 45, 50, 55, 60]])
print(x)
print(type(x))

#create array with range from 100 to 150
y = np.array([[0, 100, 105, 110, 115, 120], [125, 130, 135, 140, 145, 150]])
print(y)


#create array with input from user
n = int(input("Enter the number of elements you want in Array Z: "))
z = np.array([int(input(f"Enter element {i+1}: ")) for i in range(n)])  # Taking n inputs from user
print("Array Z (User  Input):", z)


#x+y
if len(x) < len(y):
    x = np.pad(x, (0, len(y) - len(x)), 'constant')
elif len(y) < len(x):
    y = np.pad(y, (0, len(x) - len(y)), 'constant')

result_x_plus_y = x + y
print("Result of X + Y:", result_x_plus_y)

# X * Z
result_x_times_z = x * z
print("Result of X * Z:", result_x_times_z)

#z - y
result_z_minus_y = z - y
print("Result of Z - Y:", result_z_minus_y)


#x +y+z
result_x_plus_y_plus_z = x + y + z
print("Result of X + Y + Z:", result_x_plus_y_plus_z)

[[ 5 10 15 20 25 30]
 [35 40 45 50 55 60]]
<class 'numpy.ndarray'>
[[  0 100 105 110 115 120]
 [125 130 135 140 145 150]]


Enter the number of elements you want in Array Z:  6
Enter element 1:  0
Enter element 2:  0
Enter element 3:  0
Enter element 4:  0
Enter element 5:  0
Enter element 6:  0


Array Z (User  Input): [0 0 0 0 0 0]
Result of X + Y: [[  5 110 120 130 140 150]
 [160 170 180 190 200 210]]
Result of X * Z: [[0 0 0 0 0 0]
 [0 0 0 0 0 0]]
Result of Z - Y: [[   0 -100 -105 -110 -115 -120]
 [-125 -130 -135 -140 -145 -150]]
Result of X + Y + Z: [[  5 110 120 130 140 150]
 [160 170 180 190 200 210]]


## 8.2 READING CSV (Follow)

**Learning Objectives:**

1. Understand how to read CSV into arrays.
2. Understand the data type of csv files.
3. Learn to manipulate CSV data.

In [46]:
"""
Add comments for you own reference
"""

import numpy as np

data = np.loadtxt("test.csv",delimiter=",", dtype=int)
print(data)

[[53 28 85 13 57 72 46 31 73 32]
 [50 90 87 98 82 35 86 30  2 43]
 [74 53 77  1 69 97 76 21 75  3]
 [61 67  7 21  6 55 63 42 77  6]
 [58 82 77  7 68 93 41 75 77 19]
 [59 55 52 63 12 74 11  7 84 40]
 [12 11 46 30 85 46 73 79 31 35]
 [77 20 56 32 21 83 30 32 83 24]
 [24 80 21 79 72 18 16 44 51 61]
 [63 64 95 29 69 52 81 64 92 65]
 [40  9 25 88 61 86 93 77 74 73]
 [81 58 13 30 41 41 50 44 90  1]
 [87 37 73 14 10 11 21 84 68 22]
 [33  6 82 37 92 32 83  1 58 79]
 [61 53 64 77 19 56 44 31 78 93]
 [51 34 46 54 13 72 48 65 19 83]
 [33 41 58 45 41 66 22 17 40 59]
 [37 38 10  3 89 14 12 22  1  3]
 [96 69 80 85  6 12 34 69 80 59]
 [67 90 93 69 73 89 47 98 73 57]
 [66 97  7 18 39 84  4 26 21 81]
 [20 66 56 59 66 53  2 64 73 12]
 [89  8 26 29 49 82 39 22 31 33]
 [49 76 11 30 28 21 18 57 95 69]
 [92 81 85 26 21  7 58 48 47 56]
 [37 80 41 91 59 28 85  6 68 74]
 [26 90 31 28 23 45 18 23 67 53]
 [83 17 30 50 92 23 76  7 33 67]
 [69 20 46 89 42 30 67 36 26 49]
 [83 61 82  6 30 22 34 75 64 78]
 [86 18 80

In [44]:
"""
Add comments for you own reference
"""

print("Type -",type(data))
print("Data Type -",data.dtype)
print("Size -",data.size)
print("ItemSize -",data.itemsize)
print("Dimensions -",data.ndim)
print("Shape -",data.shape)

Type - <class 'numpy.ndarray'>
Data Type - int32
Size - 1000
ItemSize - 4
Dimensions - 2
Shape - (100, 10)


**Evaluation:**

After running this program, think about and answer these questions:

1. Search for alternate methods of loading.
2. What is the use of delimiter parameter? Delimiter parameters allow for data to be organized and parsed efficiently. They make extracting meaningful data easier.

## 8.2 READING CSV (Group)

Write a program that will do the following:

1. Read csv file 'test.csv'
2. Perform basic operations on 'test.csv'
    - Multiply each value by 2
    - Subtract each value by 50
3. Create an array X with same shape and random numbers
4. Add X to data
   

In [102]:
import numpy as np
import csv 


data = np.loadtxt("test.csv",delimiter=",", dtype=int)
print("Original Data")
print(data)

y = data * 2 
print("Array Y")
print(y)

z = data - 50
print("Array Z")
print(z)

x = np.random.randint(0, 100, size=(100, 10))
print("Array X")
print(x)

a = data + x
print("Array A")
print(a)

Original Data
[[53 28 85 13 57 72 46 31 73 32]
 [50 90 87 98 82 35 86 30  2 43]
 [74 53 77  1 69 97 76 21 75  3]
 [61 67  7 21  6 55 63 42 77  6]
 [58 82 77  7 68 93 41 75 77 19]
 [59 55 52 63 12 74 11  7 84 40]
 [12 11 46 30 85 46 73 79 31 35]
 [77 20 56 32 21 83 30 32 83 24]
 [24 80 21 79 72 18 16 44 51 61]
 [63 64 95 29 69 52 81 64 92 65]
 [40  9 25 88 61 86 93 77 74 73]
 [81 58 13 30 41 41 50 44 90  1]
 [87 37 73 14 10 11 21 84 68 22]
 [33  6 82 37 92 32 83  1 58 79]
 [61 53 64 77 19 56 44 31 78 93]
 [51 34 46 54 13 72 48 65 19 83]
 [33 41 58 45 41 66 22 17 40 59]
 [37 38 10  3 89 14 12 22  1  3]
 [96 69 80 85  6 12 34 69 80 59]
 [67 90 93 69 73 89 47 98 73 57]
 [66 97  7 18 39 84  4 26 21 81]
 [20 66 56 59 66 53  2 64 73 12]
 [89  8 26 29 49 82 39 22 31 33]
 [49 76 11 30 28 21 18 57 95 69]
 [92 81 85 26 21  7 58 48 47 56]
 [37 80 41 91 59 28 85  6 68 74]
 [26 90 31 28 23 45 18 23 67 53]
 [83 17 30 50 92 23 76  7 33 67]
 [69 20 46 89 42 30 67 36 26 49]
 [83 61 82  6 30 22 34 75 64 

## 8.3 STATISTICS (Follow)

**Learning Objectives:**

1. Learn to perform statistical functions on Arrays.
2. Understand how arrays provide statistical analysis.
3. Understand how to perform statistical analysis of different dimensions of an array.

In [58]:
"""
Add comments for you own reference
"""

import numpy as np

data = np.loadtxt("test.csv",delimiter=",", dtype=int)

print("Mean -")
print(data.mean())
print("Median -")
print(np.median(data))
print("Sum -")
print(np.sum(data))
print("Standard Deviation -")
print(np.std(data))
print("Variance -")
print(np.var(data))

Mean -
49.305
Median -
51.0
Sum -
49305
Standard Deviation -
28.376398203436604
Variance -
805.2199750000001


In [60]:
#https://railsware.com/blog/python-for-machine-learning-pandas-axis-explained/
"""
Add comments for you own reference
"""

print("Mean by Rows-")
print(data.mean(axis=0))  #axis 0 = row first then column
print("Mean by Column-")
print(data.mean(axis=1))  #axis 1 = column first then row

Mean by Rows-
[51.82 49.84 50.13 51.28 47.67 45.82 48.37 49.49 49.85 48.78]
Mean by Column-
[49.  60.3 54.6 40.5 59.7 45.7 44.8 45.8 46.6 67.4 62.6 44.9 42.7 50.3
 57.6 48.5 42.2 22.9 59.  75.6 44.3 47.1 40.8 45.4 52.1 56.9 40.4 47.8
 47.4 53.5 47.6 49.2 50.4 52.1 53.4 45.6 57.5 60.5 51.8 30.5 37.3 65.5
 49.1 53.  44.8 40.6 60.  62.1 44.6 33.9 54.4 41.3 50.3 38.8 60.3 41.5
 41.5 44.3 34.4 47.8 31.3 31.7 61.5 53.8 51.6 54.3 44.3 71.  41.2 52.5
 42.4 61.5 47.8 55.3 53.1 39.5 48.6 56.1 38.5 52.  55.5 50.9 50.3 39.6
 47.7 49.2 58.8 43.8 49.2 53.5 58.4 54.1 38.  66.3 58.6 37.7 51.1 50.4
 39.1 49.8]


**Evaluation:**

After running this program, think about and answer these questions:

1. What other functions are readily available? 
2. What does axis parameter do?
3. How will different functions react to changes in dimensions of the array? The program will return an error.

## 8.3 STATISTICS (Group)

Write a program that will do the following:

1. Get a number n from User (10-30)
2. Print the statistic information for every nth row of the 'test.csv'
    - Mean
    - Median
    - Sum
    - SD
    - Variance


In [134]:
import numpy as np 

data = np.loadtxt("test.csv",delimiter=",", dtype=int)

n = np.random.randint(10, 30, size=(100, 10))
print(n)

print("Mean by Rows-")
print(n.mean(axis=0))  #axis 0 = row first then column
print("Mean by Column-")
print(n.mean(axis=1))  #axis 1 = column first then row
print("Median -")
print(np.median(data))
print("Sum -")
print(np.sum(data))
print("Standard Deviation -")
print(np.std(data))
print("Variance -")
print(np.var(data))


[[21 23 27 13 26 22 17 12 28 22]
 [23 14 25 24 15 28 18 12 15 27]
 [21 29 12 23 13 29 20 16 17 11]
 [11 20 20 20 12 28 15 23 29 17]
 [23 26 22 17 23 15 21 11 29 23]
 [10 27 15 17 29 18 21 18 10 12]
 [15 29 18 21 24 10 18 20 14 25]
 [13 26 28 23 14 25 19 26 23 29]
 [11 16 23 29 28 18 13 20 16 10]
 [20 21 25 20 16 12 27 18 22 14]
 [25 12 22 11 24 15 24 27 24 26]
 [23 13 17 20 20 11 17 17 12 26]
 [11 21 13 19 27 25 13 15 21 26]
 [25 25 10 18 17 19 24 18 28 18]
 [18 27 10 12 16 11 17 14 26 23]
 [24 29 23 27 16 28 23 21 13 11]
 [20 20 14 20 10 29 21 23 29 28]
 [21 18 21 10 19 22 13 20 20 13]
 [22 19 26 12 16 21 15 12 21 23]
 [11 21 29 29 20 26 21 14 28 13]
 [24 16 19 29 27 18 26 25 10 14]
 [28 13 16 24 11 28 17 11 16 28]
 [21 22 28 17 29 23 22 19 26 26]
 [17 16 23 21 24 20 19 13 11 24]
 [19 18 22 20 14 17 19 25 28 21]
 [27 17 13 13 14 13 16 16 15 20]
 [19 11 17 27 18 14 22 29 16 12]
 [23 29 25 23 14 22 28 13 19 27]
 [17 10 10 22 23 16 17 24 14 12]
 [13 17 12 19 18 23 14 18 23 16]
 [28 25 10

In [144]:
import numpy as np

def get_statistics_for_nth_rows(file_path, n):
    # Load the CSV file into a NumPy array
    data = np.loadtxt("test.csv", delimiter=',', dtype= int)  

    # Check if n is within the valid range
    if n < 10 or n > 30:
        print("Please enter a number between 10 and 30.")
        return

    # Iterate over every nth row
    for i in range(0, data.shape[0], n):
        row = data[i]

        # Calculate statistics
        mean = np.mean(row)
        median = np.median(row)
        total_sum = np.sum(row)
        std_dev = np.std(row)
        variance = np.var(row)

        # Print statistics
        print(f"Statistics for row {i}:")
        print(f"Mean: {mean}")
        print(f"Median: {median}")
        print(f"Sum: {total_sum}")
        print(f"Standard Deviation: {std_dev}")
        print(f"Variance: {variance}")
        print("-" * 40)

# Get user input
try:
    n = int(input("Enter a number between 10 and 30: "))
    file_path = 'test.csv' 
    get_statistics_for_nth_rows(file_path, n)
except ValueError:
    print("Invalid input. Please enter a valid integer.")

Enter a number between 10 and 30:  12


Statistics for row 0:
Mean: 49.0
Median: 49.5
Sum: 490
Standard Deviation: 22.0
Variance: 484.0
----------------------------------------
Statistics for row 12:
Mean: 42.7
Median: 29.5
Sum: 427
Standard Deviation: 30.093354748183195
Variance: 905.61
----------------------------------------
Statistics for row 24:
Mean: 52.1
Median: 52.0
Sum: 521
Standard Deviation: 26.990553903171385
Variance: 728.49
----------------------------------------
Statistics for row 36:
Mean: 57.5
Median: 61.0
Sum: 575
Standard Deviation: 24.5855648704682
Variance: 604.45
----------------------------------------
Statistics for row 48:
Mean: 44.6
Median: 43.5
Sum: 446
Standard Deviation: 23.862941981239448
Variance: 569.44
----------------------------------------
Statistics for row 60:
Mean: 31.3
Median: 20.5
Sum: 313
Standard Deviation: 25.47174905655283
Variance: 648.81
----------------------------------------
Statistics for row 72:
Mean: 47.8
Median: 48.0
Sum: 478
Standard Deviation: 28.732559927719635
Varian

## 8.4 INDEXING (Follow)

**Learning Objectives:**

1. Understand how Indexing in arrays works.
2. Understand how slicing in arrays works.
3. Learn to extract relevant information from numpy array.

In [146]:
"""
Add comments for you own reference
"""

import numpy as np

data = np.loadtxt("test.csv",delimiter=",", dtype=int)

print('Item at index (20,4):\n',data[20,4],'\n')

Item at index (20,4):
 39 



In [148]:
"""
Add comments for you own reference
"""

print('Slice of rows 20 - 24:\n',data[20:25],'\n')
    
print('Specific rows (multiples of 10):\n',data[[i for i in range(0,100,10)]],'\n')

print('Specific rows (multiples of 10):\n',data[0:100:10],'\n')

Slice of rows 20 - 24:
 [[66 97  7 18 39 84  4 26 21 81]
 [20 66 56 59 66 53  2 64 73 12]
 [89  8 26 29 49 82 39 22 31 33]
 [49 76 11 30 28 21 18 57 95 69]
 [92 81 85 26 21  7 58 48 47 56]] 

Specific rows (multiples of 10):
 [[53 28 85 13 57 72 46 31 73 32]
 [40  9 25 88 61 86 93 77 74 73]
 [66 97  7 18 39 84  4 26 21 81]
 [86 18 80 32 77 54  2 17 75 35]
 [42  8 78 74 99  5  3  3 48 13]
 [45 99 25 94 38 80 22 15 59 67]
 [17  8 24 88 35 17 45 62  2 15]
 [26 69  9 85 20 51 66  7 81 10]
 [97 90 69 73 28 13 68 41 12 64]
 [59 70 25 94 67  2 87 65 53 62]] 

Specific rows (multiples of 10):
 [[53 28 85 13 57 72 46 31 73 32]
 [40  9 25 88 61 86 93 77 74 73]
 [66 97  7 18 39 84  4 26 21 81]
 [86 18 80 32 77 54  2 17 75 35]
 [42  8 78 74 99  5  3  3 48 13]
 [45 99 25 94 38 80 22 15 59 67]
 [17  8 24 88 35 17 45 62  2 15]
 [26 69  9 85 20 51 66  7 81 10]
 [97 90 69 73 28 13 68 41 12 64]
 [59 70 25 94 67  2 87 65 53 62]] 



In [150]:
"""
Add comments for you own reference
"""

print('Slice of columns 5 - 7:\n',data[:,5:8],'\n')
print('Specific columns (multiples of 2):\n',data[:,[i for i in range(0,10,2)]],'\n')

Slice of columns 5 - 7:
 [[72 46 31]
 [35 86 30]
 [97 76 21]
 [55 63 42]
 [93 41 75]
 [74 11  7]
 [46 73 79]
 [83 30 32]
 [18 16 44]
 [52 81 64]
 [86 93 77]
 [41 50 44]
 [11 21 84]
 [32 83  1]
 [56 44 31]
 [72 48 65]
 [66 22 17]
 [14 12 22]
 [12 34 69]
 [89 47 98]
 [84  4 26]
 [53  2 64]
 [82 39 22]
 [21 18 57]
 [ 7 58 48]
 [28 85  6]
 [45 18 23]
 [23 76  7]
 [30 67 36]
 [22 34 75]
 [54  2 17]
 [99 66 53]
 [83  6 23]
 [65 92 56]
 [32 16 95]
 [29 10 60]
 [99 32 71]
 [51 91 86]
 [44 51 36]
 [66 17 29]
 [ 5  3  3]
 [72 62 73]
 [10 77 91]
 [ 8 75 44]
 [ 4  1 78]
 [32 60 63]
 [ 8  2 32]
 [66 22 97]
 [51 36 78]
 [ 2 40 10]
 [80 22 15]
 [69 24 76]
 [61 16 68]
 [55 23 68]
 [66 46 24]
 [74  7 86]
 [23 69 51]
 [34 96 42]
 [ 3 62 26]
 [10 65 95]
 [17 45 62]
 [ 5  4 47]
 [98 83 53]
 [22  5 41]
 [70 88  6]
 [65 81 97]
 [10 13  5]
 [79 93 66]
 [25 82 24]
 [67 87 66]
 [51 66  7]
 [63 38 69]
 [60 18  3]
 [12 98 86]
 [54 64 71]
 [45 46 57]
 [ 6 68 95]
 [11 26 64]
 [14 25 20]
 [11 84 88]
 [13 68 41]
 [9

In [ ]:
"""
Add comments for you own reference
"""

print('Slice of rows 20-24 & columns 5 - 7:\n',data[20:25,5:8],'\n')

**Evaluation:**

After running this program, think about and answer these questions:

1. What is the use case for slicing and indexing? Slicing and indexing allow users to find the information that is relevant to them in a quick and efficient manner. 
2. Try to manipulate the array by slicing differently.

## 8.4 INDEXING (Group)

Write a program that will do the following:

1. Use 'test.csv' 
2. Get a row and column number from the user and display the value at the index
3. Get a range of rows and columns from the user and display all rows in column range and all columns in row range and also all data in row and column range
4. Add rows 10-15 with rows 50-55 and display output

In [196]:
import numpy as np

def main():

    file_path = 'test.csv'  
    data = np.loadtxt(file_path, delimiter=',', dtype=int) 

    # Get a specific row and column number from the user
    try:
        row_index = int(input("Enter the row number: "))
        col_index = int(input("Enter the column number: "))
        value = data[row_index, col_index]
        print(f"Value at row {row_index}, column {col_index}: {value}")
    except IndexError:
        print("Invalid row or column index.")
    except ValueError:
        print("Please enter valid integers for row and column indices.")

    # Get a range of rows and columns from the user
    try:
        row_start = int(input("Enter the starting row index for the range (0-indexed): "))
        row_end = int(input("Enter the ending row index for the range (exclusive, 0-indexed): "))
        col_start = int(input("Enter the starting column index for the range (0-indexed): "))
        col_end = int(input("Enter the ending column index for the range (exclusive, 0-indexed): "))

        # Display all rows in the specified column range
        print("\nAll rows in the specified column range:")
        print(data[row_start:row_end, col_start:col_end])

        # Display all columns in the specified row range
        print("\nAll columns in the specified row range:")
        print(data[row_start:row_end, :])

        # Display all data in the specified row and column range
        print("\nAll data in the specified row and column range:")
        print(data[row_start:row_end, col_start:col_end])
    except IndexError:
        print("Invalid row or column range.")
    except ValueError:
        print("Please enter valid integers for row and column ranges.")

    # Add rows 10-15 with rows 50-55 and display output
    try:
        rows_to_add = data[10:16] + data[50:56]
        print("\nSum of rows 10-15 and 50-55:")
        print(rows_to_add)
    except IndexError:
        print("Invalid row indices for addition.")

if __name__ == "__main__":
    main()

Enter the row number:  20
Enter the column number:  4


Value at row 20, column 4: 39


Enter the starting row index for the range (0-indexed):  3
Enter the ending row index for the range (exclusive, 0-indexed):  6
Enter the starting column index for the range (0-indexed):  3
Enter the ending column index for the range (exclusive, 0-indexed):  


Please enter valid integers for row and column ranges.

Sum of rows 10-15 and 50-55:
[[ 85 108  50 182  99 166 115  92 133 140]
 [103 101  42  51  88 110  74 120 149  24]
 [132 128 161  63  25  72  37 152 134  26]
 [ 67  20  97 115 114  87 106  69  97 119]
 [123 124  97 146  84 122  90  55 158 180]
 [ 64  95 130 106  25 146  55 151  38  90]]


In [206]:
import numpy as np

data = np.loadtxt(file_path, delimiter=',', dtype=int)

row_input = int(input('row number'))
column_input = int(input('column number'))

print("Item at index :\n", data[row_input, column_input],'\n') 

row number 20
column number 4


Item at index :
 39 



In [232]:
row_range_start = int(input("row number"))
row_range_end = int(input("row number"))
column_range_start = int(input("column_number"))
column_range_end = int(input("column_number"))


print('Slice of rows  & columns :\n',data[row_range_start:row_range_end,column_range_start:column_range_end],'\n')


row number 1
row number 3
column_number 2
column_number 3


Slice of rows  & columns :
 [[87]
 [77]] 



In [226]:
row_data_10_15 = data[10:16]
row_data_50_55 = data[50:56]
rows_to_add = row_data_10_15 + row_data_50_55
print(rows_to_add)

[[ 85 108  50 182  99 166 115  92 133 140]
 [103 101  42  51  88 110  74 120 149  24]
 [132 128 161  63  25  72  37 152 134  26]
 [ 67  20  97 115 114  87 106  69  97 119]
 [123 124  97 146  84 122  90  55 158 180]
 [ 64  95 130 106  25 146  55 151  38  90]]


## 8.5 COPY VS VIEW (Follow)

**Learning Objectives:**

1. Understand the difference between a copy and a view.
2. Understand how the original array is affected when deling with views.
3. Understand how the original array is affected when deling with copies.
4. Learn to manipulate data using copies and views

In [154]:
"""
Add comments for you own reference
"""

arr = np.array([1,2,3,4,5])
print("Original Before -")
print(arr)
x = arr.view()
x[0] = 9
print("Original for view -")
print(arr)
print("View -")
print(x)
y = arr.copy()
y[1] = 8
print("Original for copy -")
print(arr)
print("Copy -")
print(y)

Original Before -
[1 2 3 4 5]
Original for view -
[9 2 3 4 5]
View -
[9 2 3 4 5]
Original for copy -
[9 2 3 4 5]
Copy -
[9 8 3 4 5]


In [156]:
"""
Add comments for you own reference
"""

data = np.loadtxt("test.csv",delimiter=",", dtype=int)
data = data[5:10]

print("Original Before -")
print(data)
x = data.view()
x[0] = 9
print("Original for view -")
print(data)
print("View -")
print(x)
y = data.copy()
y[1] = 8
print("Original for copy -")
print(data)
print("Copy -")
print(y)

Original Before -
[[59 55 52 63 12 74 11  7 84 40]
 [12 11 46 30 85 46 73 79 31 35]
 [77 20 56 32 21 83 30 32 83 24]
 [24 80 21 79 72 18 16 44 51 61]
 [63 64 95 29 69 52 81 64 92 65]]
Original for view -
[[ 9  9  9  9  9  9  9  9  9  9]
 [12 11 46 30 85 46 73 79 31 35]
 [77 20 56 32 21 83 30 32 83 24]
 [24 80 21 79 72 18 16 44 51 61]
 [63 64 95 29 69 52 81 64 92 65]]
View -
[[ 9  9  9  9  9  9  9  9  9  9]
 [12 11 46 30 85 46 73 79 31 35]
 [77 20 56 32 21 83 30 32 83 24]
 [24 80 21 79 72 18 16 44 51 61]
 [63 64 95 29 69 52 81 64 92 65]]
Original for copy -
[[ 9  9  9  9  9  9  9  9  9  9]
 [12 11 46 30 85 46 73 79 31 35]
 [77 20 56 32 21 83 30 32 83 24]
 [24 80 21 79 72 18 16 44 51 61]
 [63 64 95 29 69 52 81 64 92 65]]
Copy -
[[ 9  9  9  9  9  9  9  9  9  9]
 [ 8  8  8  8  8  8  8  8  8  8]
 [77 20 56 32 21 83 30 32 83 24]
 [24 80 21 79 72 18 16 44 51 61]
 [63 64 95 29 69 52 81 64 92 65]]


**Evaluation:**

After running this program, think about and answer these questions:

1. What does the copy() function do? It creates an array with its own separate data. Modifications to the copy do not affect the original array, and vice versa.
2. What does the view() function do? A view is a new array object that looks at the same data as the original array. Changes made to a view will affect the original array, and changes to the original will affect the view.
3. How is the original array affected by manipulating views / copies? Modifications to the copy do not affect the original array, and vice versa. Changes made to a view will affect the original array, and changes to the original will affect the view.
4. What is the best use case for views? Use views when you want to access or modify data without the overhead of copying, such as when working with large datasets.
5. What is the best use case for copies?  Use copies when you need to modify an array without altering the original data.

## 8.5 COPY VS VIEW (Group)

Write a program that will do the following:

1. Read 'test.csv' 
2. Make a copy and a view of the data
3. Convert even rows of view to all 5
4. Convert odd rows of copy to all 10
5. Add Copy to view
6. Display all three Arrays

In [234]:
import numpy as np
import csv 

data = np.loadtxt("test.csv",delimiter=",", dtype=int)
x = data.view()
y = data.copy()


In [158]:

import numpy as np

def main():
    # Load the CSV file into a NumPy array
    file_path = 'test.csv' 
    data = np.genfromtxt(file_path, delimiter=',', dtype=int)  

    # Create a view and a copy of the data
    x = data.view()
    y = data.copy()

    # Convert even rows of the view to all 5
    x[::2] = 5  

    # Convert odd rows of the copy to all 10
    y[1::2] = 10  

    # Add the copy to the view
    result_data = x + y

    # Display all three arrays
    print("Original Data:")
    print(data)
    print("\nView Data (Even rows set to 5):")
    print(x)
    print("\nCopy Data (Odd rows set to 10):")
    print(y)
    print("\nResult Data (View + Copy):")
    print(result_data)

if __name__ == "__main__":
    main()

Original Data:
[[ 5  5  5  5  5  5  5  5  5  5]
 [50 90 87 98 82 35 86 30  2 43]
 [ 5  5  5  5  5  5  5  5  5  5]
 [61 67  7 21  6 55 63 42 77  6]
 [ 5  5  5  5  5  5  5  5  5  5]
 [59 55 52 63 12 74 11  7 84 40]
 [ 5  5  5  5  5  5  5  5  5  5]
 [77 20 56 32 21 83 30 32 83 24]
 [ 5  5  5  5  5  5  5  5  5  5]
 [63 64 95 29 69 52 81 64 92 65]
 [ 5  5  5  5  5  5  5  5  5  5]
 [81 58 13 30 41 41 50 44 90  1]
 [ 5  5  5  5  5  5  5  5  5  5]
 [33  6 82 37 92 32 83  1 58 79]
 [ 5  5  5  5  5  5  5  5  5  5]
 [51 34 46 54 13 72 48 65 19 83]
 [ 5  5  5  5  5  5  5  5  5  5]
 [37 38 10  3 89 14 12 22  1  3]
 [ 5  5  5  5  5  5  5  5  5  5]
 [67 90 93 69 73 89 47 98 73 57]
 [ 5  5  5  5  5  5  5  5  5  5]
 [20 66 56 59 66 53  2 64 73 12]
 [ 5  5  5  5  5  5  5  5  5  5]
 [49 76 11 30 28 21 18 57 95 69]
 [ 5  5  5  5  5  5  5  5  5  5]
 [37 80 41 91 59 28 85  6 68 74]
 [ 5  5  5  5  5  5  5  5  5  5]
 [83 17 30 50 92 23 76  7 33 67]
 [ 5  5  5  5  5  5  5  5  5  5]
 [83 61 82  6 30 22 34 75 64

In [252]:
data = np.loadtxt("test.csv", delimiter="," , dtype=int)
data = data[5:10]

print("Orginal Before -")

x = data.view()
y = data.copy()

print(x)
#for i in range(0,len(x),):
x[::2] = 5
print(x)
y[1::2] = 10  
print(y)



Orginal Before -
[[59 55 52 63 12 74 11  7 84 40]
 [12 11 46 30 85 46 73 79 31 35]
 [77 20 56 32 21 83 30 32 83 24]
 [24 80 21 79 72 18 16 44 51 61]
 [63 64 95 29 69 52 81 64 92 65]]
[[ 5  5  5  5  5  5  5  5  5  5]
 [12 11 46 30 85 46 73 79 31 35]
 [ 5  5  5  5  5  5  5  5  5  5]
 [24 80 21 79 72 18 16 44 51 61]
 [ 5  5  5  5  5  5  5  5  5  5]]
[[59 55 52 63 12 74 11  7 84 40]
 [10 10 10 10 10 10 10 10 10 10]
 [77 20 56 32 21 83 30 32 83 24]
 [10 10 10 10 10 10 10 10 10 10]
 [63 64 95 29 69 52 81 64 92 65]]


## 8.6 MODIFICATION (Follow)

**Learning Objectives:**

1. Understand how to modify an array.
2. Learn modification functions.
3. Understand the use of array modification

In [160]:
"""
Add comments for you own reference
"""

import numpy as np
arr = np.array([1,2,3,4,5,6])
print('arr = \n',arr,"\n")
arr.resize(2,3) #view
print('arr = \n',arr,"\n")
x = arr.reshape(3,2) #copy
print('x = \n', x,"\n")

y = x.flatten()  #copy
z = x.ravel()    #view
y[0] = 99
z[0] = 88
print('x = \n', x,"\n")
print('y = \n', y,"\n")
print('z = \n', z,"\n")
print(x.transpose(),"\n")
print(x)

arr = 
 [1 2 3 4 5 6] 

arr = 
 [[1 2 3]
 [4 5 6]] 

x = 
 [[1 2]
 [3 4]
 [5 6]] 

x = 
 [[88  2]
 [ 3  4]
 [ 5  6]] 

y = 
 [99  2  3  4  5  6] 

z = 
 [88  2  3  4  5  6] 

[[88  3  5]
 [ 2  4  6]] 

[[88  2]
 [ 3  4]
 [ 5  6]]


In [162]:
"""
Add comments for you own reference
"""

data = np.loadtxt("test.csv",delimiter=",", dtype=str).astype(int)
data = data[25:30]

data.resize(25,2)
print('data = \n', data,"\n")
x = data.reshape(10,5)
print('x = \n', x,"\n")
y = x.flatten()
z = x.ravel()
y[0] = 99
z[0] = 88
print('x = \n', x,"\n")
print('y = \n', y,"\n")
print('z = \n', z,"\n")
print(x.transpose(),"\n")

data = 
 [[37 80]
 [41 91]
 [59 28]
 [85  6]
 [68 74]
 [26 90]
 [31 28]
 [23 45]
 [18 23]
 [67 53]
 [83 17]
 [30 50]
 [92 23]
 [76  7]
 [33 67]
 [69 20]
 [46 89]
 [42 30]
 [67 36]
 [26 49]
 [83 61]
 [82  6]
 [30 22]
 [34 75]
 [64 78]] 

x = 
 [[37 80 41 91 59]
 [28 85  6 68 74]
 [26 90 31 28 23]
 [45 18 23 67 53]
 [83 17 30 50 92]
 [23 76  7 33 67]
 [69 20 46 89 42]
 [30 67 36 26 49]
 [83 61 82  6 30]
 [22 34 75 64 78]] 

x = 
 [[88 80 41 91 59]
 [28 85  6 68 74]
 [26 90 31 28 23]
 [45 18 23 67 53]
 [83 17 30 50 92]
 [23 76  7 33 67]
 [69 20 46 89 42]
 [30 67 36 26 49]
 [83 61 82  6 30]
 [22 34 75 64 78]] 

y = 
 [99 80 41 91 59 28 85  6 68 74 26 90 31 28 23 45 18 23 67 53 83 17 30 50
 92 23 76  7 33 67 69 20 46 89 42 30 67 36 26 49 83 61 82  6 30 22 34 75
 64 78] 

z = 
 [88 80 41 91 59 28 85  6 68 74 26 90 31 28 23 45 18 23 67 53 83 17 30 50
 92 23 76  7 33 67 69 20 46 89 42 30 67 36 26 49 83 61 82  6 30 22 34 75
 64 78] 

[[88 28 26 45 83 23 69 30 83 22]
 [80 85 90 18 17 76 20 67 61

In [248]:
"""
flatten and ravel on a 2d array
"""

data = np.loadtxt("test.csv",delimiter=",", dtype=str).astype(int)
data = data[25:30]

data.resize(25,2)
print("original data resized\n",data,"\n")
x = data.reshape(10,5)
print("reshape of data\n", x,"\n")
y = x.flatten()
z = x.ravel()
y[0] = 99
z[0] = 88
print("reshape\n", x,"\n")
print("flatten\n",y,"\n")
print("ravel\n",z,"\n")
print("transpose\n",x.transpose(),"\n")

original data resized
 [[37 80]
 [41 91]
 [59 28]
 [85  6]
 [68 74]
 [26 90]
 [31 28]
 [23 45]
 [18 23]
 [67 53]
 [83 17]
 [30 50]
 [92 23]
 [76  7]
 [33 67]
 [69 20]
 [46 89]
 [42 30]
 [67 36]
 [26 49]
 [83 61]
 [82  6]
 [30 22]
 [34 75]
 [64 78]] 

reshape of data
 [[37 80 41 91 59]
 [28 85  6 68 74]
 [26 90 31 28 23]
 [45 18 23 67 53]
 [83 17 30 50 92]
 [23 76  7 33 67]
 [69 20 46 89 42]
 [30 67 36 26 49]
 [83 61 82  6 30]
 [22 34 75 64 78]] 

reshape
 [[88 80 41 91 59]
 [28 85  6 68 74]
 [26 90 31 28 23]
 [45 18 23 67 53]
 [83 17 30 50 92]
 [23 76  7 33 67]
 [69 20 46 89 42]
 [30 67 36 26 49]
 [83 61 82  6 30]
 [22 34 75 64 78]] 

flatten
 [99 80 41 91 59 28 85  6 68 74 26 90 31 28 23 45 18 23 67 53 83 17 30 50
 92 23 76  7 33 67 69 20 46 89 42 30 67 36 26 49 83 61 82  6 30 22 34 75
 64 78] 

ravel
 [88 80 41 91 59 28 85  6 68 74 26 90 31 28 23 45 18 23 67 53 83 17 30 50
 92 23 76  7 33 67 69 20 46 89 42 30 67 36 26 49 83 61 82  6 30 22 34 75
 64 78] 

transpose
 [[88 28 26 45 83 2

**Evaluation:**

After running this program, think about and answer these questions:

1. What is the difference between resize and reshape? Resizing arrays changes the shape without changing the data. Reshaping arrays doesn't change the data but only how it is interpreted. 
2. What is the difference between ravel and flatten? Ravel returns a view and flatten returns a new array. 
3. What does transpose() function do? It changes rows to columns and columns to rows.
4. How are these functions helpful in data analysis or statistics? It is helpful when modifying large data sets. 

## 8.6 MODIFICATION (Group)

Write a program that will do the following:

1. Read 'test.csv' 
2. Slice a 5 X 8 grid from the array (X)
3. Make a copy and transpose (X)
4. Reshape both arrays to (4,10)
5. Multiply the arrays and display the Output
6. Try to display each step

In [180]:
import numpy as np

def main():
    # Step 1: Load the CSV file into a NumPy array
    file_path = 'test.csv'  # Replace with your CSV file path
    data = np.genfromtxt(file_path, delimiter=',', dtype=int)  

    # Step 2: Slice a 5x8 grid from the array
    # Assuming the original data has at least 5 rows and 8 columns
    X = data[:5, :8]
    print("Step 2: 5x8 Grid (X):")
    print(X)

    # Step 3: Make a copy and transpose (X)
    X_copy = X.copy()
    X_transpose = X_copy.T
    print("\nStep 3: Transposed Copy of X:")
    print(X_transpose)

    # Step 4: Reshape both arrays to (4, 10)
    X_reshaped = X.reshape(4, 10)
    X_transpose_reshaped = X_transpose.reshape(4, 10)
    print("\nStep 4: Reshaped X (4, 10):")
    print(X_reshaped)
    print("\nStep 4: Reshaped Transposed X (4, 10):")
    print(X_transpose_reshaped)

    # Step 5: Multiply the arrays and display the output
    result = X_reshaped * X_transpose_reshaped  # Using matrix multiplication
    print("\nStep 5: Result of Multiplication:")
    print(result)

if __name__ == "__main__":
    main()

Step 2: 5x8 Grid (X):
[[53 28 85 13 57 72 46 31]
 [50 90 87 98 82 35 86 30]
 [74 53 77  1 69 97 76 21]
 [61 67  7 21  6 55 63 42]
 [58 82 77  7 68 93 41 75]]

Step 3: Transposed Copy of X:
[[53 50 74 61 58]
 [28 90 53 67 82]
 [85 87 77  7 77]
 [13 98  1 21  7]
 [57 82 69  6 68]
 [72 35 97 55 93]
 [46 86 76 63 41]
 [31 30 21 42 75]]

Step 4: Reshaped X (4, 10):
[[53 28 85 13 57 72 46 31 50 90]
 [87 98 82 35 86 30 74 53 77  1]
 [69 97 76 21 61 67  7 21  6 55]
 [63 42 58 82 77  7 68 93 41 75]]

Step 4: Reshaped Transposed X (4, 10):
[[53 50 74 61 58 28 90 53 67 82]
 [85 87 77  7 77 13 98  1 21  7]
 [57 82 69  6 68 72 35 97 55 93]
 [46 86 76 63 41 31 30 21 42 75]]

Step 5: Result of Multiplication:
[[2809 1400 6290  793 3306 2016 4140 1643 3350 7380]
 [7395 8526 6314  245 6622  390 7252   53 1617    7]
 [3933 7954 5244  126 4148 4824  245 2037  330 5115]
 [2898 3612 4408 5166 3157  217 2040 1953 1722 5625]]


In [254]:


data = np.loadtxt("test.csv",delimiter=",", dtype=str).astype(int)
data = data[0:5,0:8]
#print( data)
x = data
y = data.copy()
##print(x.transpose(),"\n")

x_transpose = x.transpose()
print(x)
print("after transposition")
print(x_transpose)
new_x = x.reshape(4,10)
print(new_x)
new_y = y.reshape(4,10)
print(new_x * new_y)

[[53 28 85 13 57 72 46 31]
 [50 90 87 98 82 35 86 30]
 [74 53 77  1 69 97 76 21]
 [61 67  7 21  6 55 63 42]
 [58 82 77  7 68 93 41 75]]
after transposition
[[53 50 74 61 58]
 [28 90 53 67 82]
 [85 87 77  7 77]
 [13 98  1 21  7]
 [57 82 69  6 68]
 [72 35 97 55 93]
 [46 86 76 63 41]
 [31 30 21 42 75]]
[[53 28 85 13 57 72 46 31 50 90]
 [87 98 82 35 86 30 74 53 77  1]
 [69 97 76 21 61 67  7 21  6 55]
 [63 42 58 82 77  7 68 93 41 75]]
[[2809  784 7225  169 3249 5184 2116  961 2500 8100]
 [7569 9604 6724 1225 7396  900 5476 2809 5929    1]
 [4761 9409 5776  441 3721 4489   49  441   36 3025]
 [3969 1764 3364 6724 5929   49 4624 8649 1681 5625]]
