# Workshop 8 [Solutions]

This notebook will cover the following topics:

1. Numpy Array
2. Reading data from CSV
3. Statistics
4. Indexing
5. Copy vs View
6. Modifications

## 8.1 NUMPY ARRAY (Follow)

**Learning Objectives:**

1. Understand the numpy module.
2. Understand numpy arrays.
3. Understand Array creation and basic functions.
4. Learn to manipulate arrays

In [2]:
#https://numpy.org/doc/stable/reference/arrays.dtypes.html
#https://pythonguides.com/python-numpy-data-types/
"""
Add comments for you own reference
"""

import numpy as np
x = np.array([[1,2,3,4,5],
                 [6,7,8,9,0],
                 [5,4,3,2,1]])
print(x)
print("Type -",type(x))
print("Data Type -",x.dtype)
print("Size -",x.size)
print("ItemSize -",x.itemsize)
print("Dimensions -",x.ndim)
print("Shape -",x.shape)

[[1 2 3 4 5]
 [6 7 8 9 0]
 [5 4 3 2 1]]
Type - <class 'numpy.ndarray'>
Data Type - int32
Size - 15
ItemSize - 4
Dimensions - 2
Shape - (3, 5)


In [ ]:
"""
Add comments for you own reference
"""

import numpy as np
x = np.full(5,3)
print("Full:\n",x)
x = np.zeros((2,4))
print("Zeros:\n",x)
x = np.ones((2,5))
print("Ones:\n",x)
x = np.arange(1,7)
print("Range:\n",x)
x = np.linspace(1,5,6)
print("LinSpace:\n",x)

In [ ]:
"""
Add comments for you own reference
"""

import numpy as np
x = np.arange(1,10)
print("Array X:\n",x,"\n")
print("Multiplication:\n",x*2,"\n")
print("Substraction:\n",x-2,"\n")
y = np.arange(3,12)
print("Array Y:\n",y,"\n")
print("SHAPES -",x.shape,y.shape,"\n")
print("Addition:\n",x+y,"\n")
print("Multiplication:\n",x*y,"\n")

**Evaluation:**

After running this program, think about and answer these questions:

1. What does the arange function do?
2. What is the use of 1s and 0s function?
3. What will happen if shapes of arrays are not same?
4. Try to add more dimentions to the arrays.

## 8.1 NUMPY ARRAY (Group)

Write a program that will do the following:

1. Create 3 Arrays:
    - X : containing Multiples of 5
    - Y : in range of 100 to 150
    - Z : containing all n (taken from user) 
2. Make sure that Shapes of arrays are equal.
3. Perform:
    - X + Y
    - X * Z
    - Z - Y
    - X + Y + Z

In [ ]:
"""
Add comments for you own reference
"""
import numpy as np
import random as r

xlist = [i*5 for i in range(1,11)]
x = np.array(xlist)
print(x)

ylist = [r.randint(100,150) for i in range(10)]
y = np.array(ylist)
print(y)

z = np.full(10,int(input("Enter Number: ")))
print(z)

print("\nSHAPES:")
print(x.shape)
print(y.shape)
print(z.shape)

print("\nCALCULATIONS:")
print("X+Y = ",x+y)
print("X*Z = ",x*z)
print("Z-Y = ",z-y)
print("X+Y+Z = ",x+y+z)

## 8.2 READING CSV (Follow)

**Learning Objectives:**

1. Understand how to read CSV into arrays.
2. Understand the data type of csv files.
3. Learn to manipulate CSV data.

In [ ]:
#https://numpy.org/doc/stable/reference/generated/numpy.loadtxt.html
"""
Add comments for you own reference
"""

import numpy as np

data = np.loadtxt("test.csv",delimiter=",", dtype=int)
print(data)

In [ ]:
"""
Add comments for you own reference
"""

print("Type -",type(data))
print("Data Type -",data.dtype)
print("Size -",data.size)
print("ItemSize -",data.itemsize)
print("Dimensions -",data.ndim)
print("Shape -",data.shape)

**Evaluation:**

After running this program, think about and answer these questions:

1. Search for alternate methods of loading.
2. What is the use of delimiter parameter?

## 8.2 READING CSV (Group)

Write a program that will do the following:

1. Read csv file 'test.csv'
2. Perform basic operations on 'test.csv'
    - Multiply each value by 2
    - Subtract each value by 50
3. Create an array X with same shape and random numbers
4. Add X to data
   

In [ ]:
"""
Add comments for you own reference
"""

import numpy as np
import random as r

data = np.loadtxt("test.csv",delimiter=",", dtype=int)

print(data.shape)

two = np.full((100,10),2)

fifty = np.full((100,10),50)

rlist = []
for i in range(100):
    rlist.append([r.randint(1,100) for j in range(10)])

x = np.array(rlist)

data = data * two

data = data - fifty

data += x

print(data)

## 8.3 STATISTICS (Follow)

**Learning Objectives:**

1. Learn to perform statistical functions on Arrays.
2. Understand how arrays provide statistical analysis.
3. Understand how to perform statistical analysis of different dimensions of an array.

In [ ]:
"""
Add comments for you own reference
"""

import numpy as np

data = np.loadtxt("test.csv",delimiter=",", dtype=int)

print("Mean -")
print(data.mean())
print("Median -")
print(np.median(data))
print("Sum -")
print(np.sum(data[0]))
print("Standard Deviation -")
print(np.std(data))
print("Variance -")
print(np.var(data))

In [ ]:
#https://railsware.com/blog/python-for-machine-learning-pandas-axis-explained/
"""
Add comments for you own reference
"""

print("Mean by Rows-")
print(data.mean(axis=0))
print("Mean by Column-")
print(data.mean(axis=1))

**Evaluation:**

After running this program, think about and answer these questions:

1. What other functions are readily available?
2. What does axis parameter do?
3. How will different functions react to changes in dimensions of the array?

## 8.3 STATISTICS (Group)

Write a program that will do the following:

1. Get a number n from User (10-30)
2. Print the statistic information for every nth row of the 'test.csv'
    - Mean
    - Median
    - Sum
    - SD
    - Variation


In [ ]:
"""
Add comments for you own reference
"""

import numpy as np

num = n = int(input("Enter number between 10 -30: "))
data = np.loadtxt("test.csv",delimiter=",", dtype=int)


while n < len(data):
    print(f"Mean of {n}th -")
    print(data[n].mean())
    print(f"Median of {n}th -")
    print(np.median(data[n]))
    print(f"Sum of {n}th -")
    print(np.sum(data[n]))
    print(f"Standard Deviation of {n}th -")
    print(np.std(data[n]))
    print(f"Variation of {n}th -")
    print(np.var(data[n]))
    print()
    n+= num
    

## 8.4 INDEXING (Follow)

**Learning Objectives:**

1. Understand how Indexing in arrays works.
2. Understand how slicing in arrays works.
3. Learn to extract relevant information from numpy array.

In [ ]:
"""
Add comments for you own reference
"""

import numpy as np

data = np.loadtxt("test.csv",delimiter=",", dtype=int)

print('Item at index (20,4):\n',data[20,4],'\n')

In [ ]:
"""
Add comments for you own reference
"""

print('Slice of rows 20 - 24:\n',data[20:25],'\n')
print('Specific rows (multiples of 10):\n',data[[i for i in range(0,100,10)]],'\n')

In [ ]:
"""
Add comments for you own reference
"""

print('Slice of columns 5 - 7:\n',data[:,5:8],'\n')
print('Specific columns (multiples of 2):\n',data[:,[i for i in range(0,10,2)]],'\n')

In [ ]:
"""
Add comments for you own reference
"""

print('Slice of rows 20-24 & columns 5 - 7:\n',data[20:25,5:8],'\n')

**Evaluation:**

After running this program, think about and answer these questions:

1. What is the use case for slicing and indexing?
2. Try to manipulate the array by slicing differently.

## 8.4 INDEXING (Group)

Write a program that will do the following:

1. Use 'test.csv' 
2. Get a row and column number from the user and display the value at the index
3. Get a range of rows and columns from the user and display all rows in column range and all columns in row range and also all data in row and column range
4. Add rows 10-15 with rows 50-55 and display output

In [ ]:
"""
Add comments for you own reference
"""

import numpy as np
data = np.loadtxt("test.csv",delimiter=",", dtype=int)

print(data.shape)

row = int(input("Enter row number: "))
col = int(input("Enter column number: "))

print(data[row,col])

row2 = int(input(f"Enter row number > {row}: "))
col2 = int(input(f"Enter column number > {col}: "))

In [ ]:
print(f"Rows {row}-{row2}")
print(data[row:row2,:])

In [ ]:
print(f"Columns {col}-{col2}")
print(data[:,col:col2])

In [ ]:
print(f"Rows {row}-{row2} AND Columns {col}-{col2}")
print(data[row:row2,col:col2])

In [ ]:
a = data[10:15]
b = data[50:55]

c = a+b
print(c)

## 8.5 COPY VS VIEW (Follow)

**Learning Objectives:**

1. Understand the difference between a copy and a view.
2. Understand how the original array is affected when deling with views.
3. Understand how the original array is affected when deling with copies.
4. Learn to manipulate data using copies and views

In [3]:
#https://data-flair.training/blogs/numpy-copy-view/
"""
Add comments for you own reference
"""

arr = np.array([1,2,3,4,5])
print("Original Before -")
print(arr)
x = arr.view()
x[0] = 9
print("Original for view -")
print(arr)
print("View -")
print(x)
y = arr.copy()
y[1] = 8
print("Original for copy -")
print(arr)
print("Copy -")
print(y)

Original Before -
[1 2 3 4 5]
Original for view -
[9 2 3 4 5]
View -
[9 2 3 4 5]
Original for copy -
[9 2 3 4 5]
Copy -
[9 8 3 4 5]


In [4]:
"""
Add comments for you own reference
"""

data = np.loadtxt("test.csv",delimiter=",", dtype=int)
data = data[5:10]

print("Original Before -")
print(data)
x = data.view()
x[0] = 9
print("Original for view -")
print(data)
print("View -")
print(x)
y = data.copy()
y[1] = 8
print("Original for copy -")
print(data)
print("Copy -")
print(y)

Original Before -
[[59 55 52 63 12 74 11  7 84 40]
 [12 11 46 30 85 46 73 79 31 35]
 [77 20 56 32 21 83 30 32 83 24]
 [24 80 21 79 72 18 16 44 51 61]
 [63 64 95 29 69 52 81 64 92 65]]
Original for view -
[[ 9  9  9  9  9  9  9  9  9  9]
 [12 11 46 30 85 46 73 79 31 35]
 [77 20 56 32 21 83 30 32 83 24]
 [24 80 21 79 72 18 16 44 51 61]
 [63 64 95 29 69 52 81 64 92 65]]
View -
[[ 9  9  9  9  9  9  9  9  9  9]
 [12 11 46 30 85 46 73 79 31 35]
 [77 20 56 32 21 83 30 32 83 24]
 [24 80 21 79 72 18 16 44 51 61]
 [63 64 95 29 69 52 81 64 92 65]]
Original for copy -
[[ 9  9  9  9  9  9  9  9  9  9]
 [12 11 46 30 85 46 73 79 31 35]
 [77 20 56 32 21 83 30 32 83 24]
 [24 80 21 79 72 18 16 44 51 61]
 [63 64 95 29 69 52 81 64 92 65]]
Copy -
[[ 9  9  9  9  9  9  9  9  9  9]
 [ 8  8  8  8  8  8  8  8  8  8]
 [77 20 56 32 21 83 30 32 83 24]
 [24 80 21 79 72 18 16 44 51 61]
 [63 64 95 29 69 52 81 64 92 65]]


**Evaluation:**

After running this program, think about and answer these questions:

1. What does the copy() function do?
2. What does the view() function do?
3. How is the original array affected by manipulating views / copies?
4. What is the best use case for views?
5. What is the best use case for copies?

## 8.5 COPY VS VIEW (Group)

Write a program that will do the following:

1. Read 'test.csv' 
2. Make a copy and a view of the data
3. Convert even rows of view to all 5
4. Convert odd rows of copy to all 10
5. Add Copy to view
6. Display all three Arrays

In [26]:
import numpy as np
data = np.loadtxt("test.csv",delimiter=",", dtype=int)
data = data[0:5, :]
data_view = data.view()
data_copy = data.copy()

for i in range(0,5,2):
    data_view[i] = 5

for i in range(1,5,2):
    data_copy[i] = 10
print(data)
print(data_copy)


data_view += data_copy
data_view = data_view + data_copy

print("\n----------------------------------")
print("data view memory location: ", data_view[0].data)
print(data_view)
print("\ndata memory location: ", data[0].data)
print(data)
print("\ndata copy memory location: ", data_copy[0].data)
print(data_copy)

[[ 5  5  5  5  5  5  5  5  5  5]
 [50 90 87 98 82 35 86 30  2 43]
 [ 5  5  5  5  5  5  5  5  5  5]
 [61 67  7 21  6 55 63 42 77  6]
 [ 5  5  5  5  5  5  5  5  5  5]]
[[53 28 85 13 57 72 46 31 73 32]
 [10 10 10 10 10 10 10 10 10 10]
 [74 53 77  1 69 97 76 21 75  3]
 [10 10 10 10 10 10 10 10 10 10]
 [58 82 77  7 68 93 41 75 77 19]]

----------------------------------
data view memory location:  <memory at 0x0000027BCCA2EC80>
[[111  61 175  31 119 149  97  67 151  69]
 [ 70 110 107 118 102  55 106  50  22  63]
 [153 111 159   7 143 199 157  47 155  11]
 [ 81  87  27  41  26  75  83  62  97  26]
 [121 169 159  19 141 191  87 155 159  43]]

data memory location:  <memory at 0x0000027BCCA2EC80>
[[ 58  33  90  18  62  77  51  36  78  37]
 [ 60 100  97 108  92  45  96  40  12  53]
 [ 79  58  82   6  74 102  81  26  80   8]
 [ 71  77  17  31  16  65  73  52  87  16]
 [ 63  87  82  12  73  98  46  80  82  24]]

data copy memory location:  <memory at 0x0000027BCCA2EC80>
[[53 28 85 13 57 72 46 31 

In [6]:
"""
Add comments for you own reference
"""

import numpy as np
data = np.loadtxt("test.csv",delimiter=",", dtype=int)

data_view = data.view()
data_copy = data.copy()

for i in range(0,100,2):
    data_view[i] = 5

for i in range(1,100,2):
    data_copy[i] = 10


data_view += data_copy

In [7]:
print(data)

[[ 58  33  90  18  62  77  51  36  78  37]
 [ 60 100  97 108  92  45  96  40  12  53]
 [ 79  58  82   6  74 102  81  26  80   8]
 [ 71  77  17  31  16  65  73  52  87  16]
 [ 63  87  82  12  73  98  46  80  82  24]
 [ 69  65  62  73  22  84  21  17  94  50]
 [ 17  16  51  35  90  51  78  84  36  40]
 [ 87  30  66  42  31  93  40  42  93  34]
 [ 29  85  26  84  77  23  21  49  56  66]
 [ 73  74 105  39  79  62  91  74 102  75]
 [ 45  14  30  93  66  91  98  82  79  78]
 [ 91  68  23  40  51  51  60  54 100  11]
 [ 92  42  78  19  15  16  26  89  73  27]
 [ 43  16  92  47 102  42  93  11  68  89]
 [ 66  58  69  82  24  61  49  36  83  98]
 [ 61  44  56  64  23  82  58  75  29  93]
 [ 38  46  63  50  46  71  27  22  45  64]
 [ 47  48  20  13  99  24  22  32  11  13]
 [101  74  85  90  11  17  39  74  85  64]
 [ 77 100 103  79  83  99  57 108  83  67]
 [ 71 102  12  23  44  89   9  31  26  86]
 [ 30  76  66  69  76  63  12  74  83  22]
 [ 94  13  31  34  54  87  44  27  36  38]
 [ 59  86  

In [8]:
print(data_copy)

[[53 28 85 13 57 72 46 31 73 32]
 [10 10 10 10 10 10 10 10 10 10]
 [74 53 77  1 69 97 76 21 75  3]
 [10 10 10 10 10 10 10 10 10 10]
 [58 82 77  7 68 93 41 75 77 19]
 [10 10 10 10 10 10 10 10 10 10]
 [12 11 46 30 85 46 73 79 31 35]
 [10 10 10 10 10 10 10 10 10 10]
 [24 80 21 79 72 18 16 44 51 61]
 [10 10 10 10 10 10 10 10 10 10]
 [40  9 25 88 61 86 93 77 74 73]
 [10 10 10 10 10 10 10 10 10 10]
 [87 37 73 14 10 11 21 84 68 22]
 [10 10 10 10 10 10 10 10 10 10]
 [61 53 64 77 19 56 44 31 78 93]
 [10 10 10 10 10 10 10 10 10 10]
 [33 41 58 45 41 66 22 17 40 59]
 [10 10 10 10 10 10 10 10 10 10]
 [96 69 80 85  6 12 34 69 80 59]
 [10 10 10 10 10 10 10 10 10 10]
 [66 97  7 18 39 84  4 26 21 81]
 [10 10 10 10 10 10 10 10 10 10]
 [89  8 26 29 49 82 39 22 31 33]
 [10 10 10 10 10 10 10 10 10 10]
 [92 81 85 26 21  7 58 48 47 56]
 [10 10 10 10 10 10 10 10 10 10]
 [26 90 31 28 23 45 18 23 67 53]
 [10 10 10 10 10 10 10 10 10 10]
 [69 20 46 89 42 30 67 36 26 49]
 [10 10 10 10 10 10 10 10 10 10]
 [86 18 80

## 8.6 MODIFICATION (Follow)

**Learning Objectives:**

1. Understand how to modify an array.
2. Learn modification functions.
3. Understand the use of array modification

In [ ]:
"""
Add comments for you own reference
"""

import numpy as np
arr = np.array([1,2,3,4,5,6])
arr.resize(2,3)
print('arr = \n',arr,"\n")

x = arr.reshape(3,2)
print('x = \n', x,"\n")
#print('arr = \n', arr, '\n')

y = x.flatten() #copy
z = x.ravel() #view
y[0] = 99
z[0] = 88
print('x = \n', x,"\n")
print('y = \n', y,"\n")
print('z = \n', z,"\n")
print(x.transpose(),"\n")

In [ ]:
"""
Add comments for you own reference
"""

data = np.loadtxt("test.csv",delimiter=",", dtype=str).astype(int)
data = data[25:30]

data.resize(25,2)
print('data = \n', data,"\n")
x = data.reshape(10,5)
print('x = \n', x,"\n")
y = x.flatten()
z = x.ravel()
y[0] = 99
z[0] = 88
print('x = \n', x,"\n")
print('y = \n', y,"\n")
print('z = \n', z,"\n")
print(x.transpose(),"\n")

**Evaluation:**

After running this program, think about and answer these questions:

1. What is the difference between resize and reshape?
2. What is the difference between ravel and flatten?
3. What does transpose() function do?
4. How are these functions helpful in data analysis or statistics?

## 8.6 MODIFICATION (Group)

Write a program that will do the following:

1. Read 'test.csv' 
2. Slice a 5 X 8 grid from the array (X)
3. Make a copy and transpose (X)
4. Reshape both arrays to (4,10)
5. Multiply the arrays and display the Output
6. Try to display each step

In [ ]:
"""
Add comments for you own reference
"""

import numpy as np
data = np.loadtxt("test.csv",delimiter=",", dtype=int)

n = int(input("Enter Number: "))

dataX = data[n:n+5,1:9]

print(dataX.shape)

dataX_copy = dataX.copy()

print("\n COPY:")
print(dataX_copy)

dataY = dataX_copy.transpose()

print("\n TRANSPOSE")
print(dataY)

X = dataX.reshape(4,10)
Y = dataY.reshape(4,10)

print("\n RESHAPED:")
print(X)
print("\n RESHAPED:")
print(Y)

ans = X * Y

print("\nANSWER")
print(ans)